name: Terraform Security Scanner

on:
  pull_request:
    branches:
      - main

# Give the robot permission to read the code AND write comments
permissions:
  pull-requests: write
  contents: read

jobs:
  tfsec_scan:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}