name: Terraform Security Scanner

# Wake the robot up whenever a Pull Request is opened
on:
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      # Step 1: The robot downloads your code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: The robot puts on its security glasses and scans the code
      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}